### ISSUE TITLE
Empty ReadMe.md? 

### ISSUE THREAD

**Issue by theo-commits** [Sehnya/Javascript-Assignments#1]
Your readme doesn't have any details and I find it very confusing. Plz fix. 

https://medium.com/@kc_clintone/the-ultimate-guide-to-writing-a-great-readme-md-for-your-project-3d49c2023357

**Comment by Sehnya** [comment]
![lil-uzi](https://github.com/user-attachments/assets/f84c43d9-f401-422f-abac-a06625ea0e1e)
